apiVersion: v1
kind: Namespace
metadata:
  name: demo-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: demo-apps

spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crawler
    spec:
      containers:
      - args:
        - |2-

          import time, math
          from datetime import datetime

          while True:
              print("Hi!")

      
        command:
        - python
        - -u
        - -c
        image: python:3.10-slim
        imagePullPolicy: IfNotPresent
        name: crawler
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 100Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crawler
  namespace: demo-apps

spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crawler
---
apiVersion: thoras.ai/v1
kind: AIScaleTarget
metadata:
  name: dummy-ast
  namespace: demo-apps
spec:
  horizontal:
    mode: auto
  model:
    forecast_blocks: 5m0s
    forecast_buffer_percentage: 0%
    forecast_cron: '*/5 * * * *'
    mode: balanced
  scaleTargetRef:
    kind: Deployment
    name: crawler
  vertical:
    containers:
    - cpu:
        lowerbound: 20m
        upperbound: 2
      memory:
        lowerbound: 10Mi
        upperbound: 2G
      name: crawler
    mode: recommendation
